version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPORT: ${POSTGRES_PORT}
    networks:
      - network
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    container_name: backend
    build:
      context: ./backend
    restart: always
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    expose:
      - ${BACKEND_PORT}
    networks:
      - network
    depends_on:
      - postgres
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    restart: always
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    expose:
      - ${FRONTEND_PORT}
    networks:
      - network
    depends_on:
      - backend

networks:
  network:
    driver: bridge

volumes:
  pgdata: